# Generated by Django 4.2.5 on 2024-04-26 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whispers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='related_conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whispers.conversion'),
        ),
    ]
